version: "3.8"

services:
  flask:
    build: .
    container_name: flask_app
    ports:
      - "5000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - web_cache_dec

  nginx:
    image: nginx:stable
    container_name: nginx_cache
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask
    networks:
      - web_cache_dec


networks:
  web_cache_dec:
    driver: bridge